import { Video, Creator } from '@/types';

export const mockCreators: Creator[] = [
  {
    id: 'creator-1',
    name: 'Luna Web3',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Luna',
    bio: 'Crypto educator & NFT enthusiast | Building the future of video',
    followers: 125000,
    isVerified: true,
    walletAddress: '0x742d35Cc6634C0532925a3b844Bc9e7595f42aE9',
    totalVideos: 342,
    totalViews: 2500000,
    createdAt: new Date('2022-01-15'),
  },
  {
    id: 'creator-2',
    name: 'Dev Nexus',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=DevNexus',
    bio: 'Blockchain developer | Smart contracts & DeFi tutorials',
    followers: 98000,
    isVerified: true,
    walletAddress: '0x8ba1f109551bD432803012645Ac136ddd64DBA72',
    totalVideos: 287,
    totalViews: 1800000,
    createdAt: new Date('2022-03-20'),
  },
  {
    id: 'creator-3',
    name: 'Alex Crypto',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=AlexCrypto',
    bio: 'Blockchain analyst | Market insights & trading strategies',
    followers: 156000,
    isVerified: true,
    walletAddress: '0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266',
    totalVideos: 451,
    totalViews: 3200000,
    createdAt: new Date('2021-06-10'),
  },
];

export const mockVideos: Video[] = [
  {
    id: 'video-1',
    title: 'Complete Guide to Smart Contracts in 2024',
    description:
      'Learn how to write, deploy, and interact with smart contracts on Ethereum, Polygon, and other blockchains. This comprehensive tutorial covers Solidity basics, testing, and real-world applications.',
    thumbnail: 'https://picsum.photos/480/270?random=1',
    videoUrl: 'https://example.com/video1.mp4',
    duration: 1245,
    views: 125000,
    likes: 4500,
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    creatorId: 'creator-1',
    creatorName: 'Luna Web3',
    creatorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Luna',
    category: 'Education',
    isFeatured: true,
    isExclusive: false,
  },
  {
    id: 'video-2',
    title: 'Building DeFi Protocols: A Step-by-Step Tutorial',
    description:
      'Discover how to create your own decentralized finance protocol. We build a lending platform from scratch using React and Solidity.',
    thumbnail: 'https://picsum.photos/480/270?random=2',
    videoUrl: 'https://example.com/video2.mp4',
    duration: 2100,
    views: 98500,
    likes: 3200,
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    creatorId: 'creator-2',
    creatorName: 'Dev Nexus',
    creatorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=DevNexus',
    category: 'Tutorial',
    isFeatured: true,
    isExclusive: true,
    membershipNFT: '0x1234567890abcdef',
  },
  {
    id: 'video-3',
    title: 'Bitcoin Price Analysis: What Happens Next?',
    description:
      'In-depth technical analysis of Bitcoin and Ethereum. Using on-chain data and chart patterns to predict market movements.',
    thumbnail: 'https://picsum.photos/480/270?random=3',
    videoUrl: 'https://example.com/video3.mp4',
    duration: 1890,
    views: 156000,
    likes: 5800,
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    creatorId: 'creator-3',
    creatorName: 'Alex Crypto',
    creatorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=AlexCrypto',
    category: 'Analysis',
    isFeatured: true,
    isExclusive: false,
  },
  {
    id: 'video-4',
    title: 'NFT Creation & Minting: The Complete Guide',
    description:
      'Learn how to create, mint, and launch your own NFT collection. Perfect for artists and creators entering Web3.',
    thumbnail: 'https://picsum.photos/480/270?random=4',
    videoUrl: 'https://example.com/video4.mp4',
    duration: 1560,
    views: 67000,
    likes: 2100,
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    creatorId: 'creator-1',
    creatorName: 'Luna Web3',
    creatorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Luna',
    category: 'NFT',
    isFeatured: false,
    isExclusive: false,
  },
  {
    id: 'video-5',
    title: 'Gas Optimization Techniques for Smart Contracts',
    description:
      'Advanced Solidity techniques to reduce gas costs. Learn about assembly, storage optimization, and more.',
    thumbnail: 'https://picsum.photos/480/270?random=5',
    videoUrl: 'https://example.com/video5.mp4',
    duration: 1345,
    views: 45000,
    likes: 1800,
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    creatorId: 'creator-2',
    creatorName: 'Dev Nexus',
    creatorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=DevNexus',
    category: 'Development',
    isFeatured: false,
    isExclusive: true,
    membershipNFT: '0x5678901234567890',
  },
  {
    id: 'video-6',
    title: 'Stake Your Crypto: Passive Income Guide',
    description:
      'Ultimate guide to staking cryptocurrencies. Learn about different staking mechanisms and maximize your returns.',
    thumbnail: 'https://picsum.photos/480/270?random=6',
    videoUrl: 'https://example.com/video6.mp4',
    duration: 978,
    views: 201000,
    likes: 7200,
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
    creatorId: 'creator-3',
    creatorName: 'Alex Crypto',
    creatorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=AlexCrypto',
    category: 'Finance',
    isFeatured: true,
    isExclusive: false,
  },
];

export const categories = [
  'All',
  'Education',
  'Tutorial',
  'Analysis',
  'NFT',
  'Development',
  'Finance',
  'News',
];
